apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: btc-difficulty-maintainer
  labels:
    app: maintainer
    type: btc-difficulty
    network: mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintainer
      type: btc-difficulty
      network: mainnet
  serviceName: btc-difficulty-maintainer
  template:
    metadata:
      labels:
        app: maintainer
        type: btc-difficulty
        network: mainnet
    spec:
      volumes:
        - name: eth-account-keyfile
          configMap:
            name: btc-difficulty-maintainer-eth-accounts-info
            items:
              - key: btc-difficulty-maintainer-keyfile
                path: btc-difficulty-maintainer-keyfile
      containers:
        - name: btc-difficulty-maintainer
          image: gcr.io/keep-prd-210b/keep-client:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1500m
              memory: 512M
          env:
            - name: LOG_LEVEL
              value: info
            - name: KEEP_ETHEREUM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: btc-difficulty-maintainer-eth-accounts-password
                  key: btc-difficulty-maintainer-password
            - name: ETH_WS_URL
              valueFrom:
                secretKeyRef:
                  name: eth-network-mainnet
                  key: ws-url
            - name: ELECTRUM_API_URL
              valueFrom:
                configMapKeyRef:
                  name: electrum-api-mainnet
                  key: electrumx-url-ssl
          volumeMounts:
            - name: eth-account-keyfile
              mountPath: /mnt/btc-difficulty-maintainer/keyfile
          command:
            - keep-client
            - maintainer
          args:
            - --bitcoinDifficulty
            - --mainnet
            - --ethereum.url
            - $(ETH_WS_URL)
            - --ethereum.keyFile
            - /mnt/btc-difficulty-maintainer/keyfile/btc-difficulty-maintainer-keyfile
            - --bitcoin.electrum.url
            - $(ELECTRUM_API_URL)
            - --bitcoin.electrum.protocol
            - "SSL"
