apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: btc-difficulty-maintainer
  labels:
    app: maintainer
    type: btc-difficulty
    network: goerli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintainer
      type: btc-difficulty
      network: goerli
  serviceName: btc-difficulty-maintainer
  #volumeClaimTemplates:
  # - metadata:
  #     name: btc-difficulty-maintainer-data
  #   spec:
  #     accessModes:
  #     - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 4096Mi
  template:
    metadata:
      labels:
        app: maintainer
        type: btc-difficulty
        network: goerli
    spec:
      volumes:
        # - name: btc-difficulty-maintainer-data
        #   persistentVolumeClaim:
        #     claimName: btc-difficulty-maintainer-data
      - name: eth-account-keyfile
        configMap:
          name: eth-account-info
          items:
          - key: account-0-keyfile
            path: account-0-keyfile
      containers:
        - name: btc-difficulty-maintainer
          image: gcr.io/keep-test-f3e0/keep-client:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1500m
              memory: 512M
          ports:
          # TODO: Fill with proper data
          env:
          - name: KEEP_ETHEREUM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eth-account-passphrases
                key: account-0
          - name: ETH_WS_URL
            valueFrom:
              secretKeyRef:
                name: eth-network-goerli
                key: ws-url
          envFrom:
          # TODO: Fill with proper data
          volumeMounts:
          - name: eth-account-keyfile
            mountPath: /mnt/keep-client/keyfile
          command:
          - keep-client
          - maintainer
          args:
          - --bitcoinDifficulty
          - --goerli
          - --ethereum.url
          - $(ETH_WS_URL)
          - --ethereum.keyFile
          - /mnt/keep-client/keyfile/account-0-keyfile
          - bitcoin.electrum.url
          - wss://electrumx-server.tbtc.network:8443
          - bitcoin.electrum.protocol
          - wss
