apiVersion: v1
kind: Service
metadata:
  name: bcoin
  labels:
    app: bitcoin-node
    type: bcoin
spec:
  ports:
    - port: 18332
      targetPort: 18332
      name: testnet-rpc
      protocol: TCP
    - port: 18333
      targetPort: 18333
      name: testnet
      protocol: TCP
  selector:
    app: bitcoin-node
    type: bcoin
