apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: btc-difficulty-maintainer
  labels:
    app: maintainer
    type: btc-difficulty
    network: goerli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintainer
      type: btc-difficulty
      network: goerli
  serviceName: btc-difficulty-maintainer
  template:
    metadata:
      labels:
        app: maintainer
        type: btc-difficulty
        network: goerli
    spec:
      volumes:
      - name: eth-account-keyfile
        configMap:
          name: btc-difficulty-maintainer-info
          items:
          - key: btc-difficulty-maintainer-keyfile
            path: btc-difficulty-maintainer-keyfile
      containers:
        - name: btc-difficulty-maintainer
          image: gcr.io/keep-test-f3e0/keep-client:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1500m
              memory: 512M
          env:
          - name: KEEP_ETHEREUM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: btc-difficulty-maintainer
                key: eth-account-password
          - name: ETH_WS_URL
            valueFrom:
              secretKeyRef:
                name: eth-network-goerli
                key: ws-url
          envFrom:
          - configMapRef:
            name: btc-difficulty-maintainer-config
          volumeMounts:
          - name: eth-account-keyfile
            mountPath: /mnt/btc-difficulty-maintainer/keyfile
          command:
          - keep-client
          - maintainer
          args:
          - --bitcoinDifficulty
          - --developer # run as developer to be able to set LightRelay address
          - --ethereum.url
          - $(ETH_WS_URL)
          - --ethereum.keyFile
          - /mnt/btc-difficulty-maintainer/keyfile/btc-difficulty-maintainer-keyfile
          - --bitcoin.electrum.url
          - wss://electrumx-server.tbtc.network:8443
          - --bitcoin.electrum.protocol
          - wss
          - --developer.LightRelayAddress 0xEf47bfE31d60c802fBA84d6E40ac266f605C8558
          # temporarily pass dummy addresses for test purposes
          - --developer.RandomBeaconAddress 0x0000000000000000000000000000000000000000
          - --developer.WalletRegistryAddress 0x0000000000000000000000000000000000000000
          - --developer.TokenStakingAddress 0x0000000000000000000000000000000000000000
