resources:
  - ../../templates/keep-maintainer

namespace: default

commonLabels:
  app: keep-maintainer
  type: all
  network: mainnet

images:
  - name: keep-maintainer
    newName: gcr.io/keep-prd-210b/keep-client
    newTag: v2.0.0-m4-rc

configMapGenerator:
  - name: keep-maintainer-config
    behavior: merge
    literals:
      - network=mainnet
      - electrum-api-url=ws://electrumx.bitcoin:8080
    files:
      - .secret/keep-maintainer-keyfile

secretGenerator:
  - name: keep-maintainer-eth-account-password
    files:
      - .secret/keep-maintainer-password

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated
