resources:
  - ../../../templates/bitcoin/bitcoind

namespace: default

configMapGenerator:
  - name: bitcoind
    behavior: merge
    literals:
      - chain=test

secretGenerator:
  - name: bitcoind
    behavior: merge
    envs:
      - .env.secret
