resources:
  - bitcoind-statefulset.yaml

configMapGenerator:
  - name: bitcoind
    literals:
      - rpc-host=bitcoind.default.svc.cluster.local:8332
      - chain=main

secretGenerator:
  - name: bitcoind
    envs:
      - .env.sample

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated
